Repository CS2113-AY1819S1-T16-2/main, pull requests merged in 2018-10, with the labels that each got.

#18 Add CreateCommand and Events UI Basics
  README.adoc
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/ui/EventPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Location.java
  src/main/java/seedu/address/model/util/SampleEventUtil.java
  src/main/java/seedu/address/storage/EventStorageManager.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageAddress.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlEventStorage.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/EventsUtil.java
Labels: priority.medium, type.enhancement

#36 Added new test case for storage manager.
  src/main/java/seedu/address/model/event/Event.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.low, severity.Low

#53 Add InviteCommand with Tests
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/InviteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/InviteCommandParser.java
  src/main/java/seedu/address/model/event/Attendees.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/storage/XmlAdaptedEvent.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/InviteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/InviteCommandParserTest.java
  src/test/java/seedu/address/model/event/AttendeesTest.java
  src/test/java/seedu/address/model/event/EventNameTest.java
  src/test/java/seedu/address/testutil/EventsUtil.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.high

#73 Make name of Person uneditable
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/InviteCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/resources/view/EventListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/InviteCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/event/AttendeesTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.medium, type.bug

#76 Change LocalDate to new EventDate
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/InviteCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/main/java/seedu/address/model/event/AttendeeContainsNamePredicate.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventContainsAttendeeAndDatePredicate.java
  src/main/java/seedu/address/model/event/EventDate.java
  src/main/java/seedu/address/model/event/TimeType.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/util/SampleEventUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedEvent.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
  src/test/java/seedu/address/model/event/AttendeeContainsNamePredicateTest.java
  src/test/java/seedu/address/model/event/EventContainsAttendeeAndDatePredicateTest.java
  src/test/java/seedu/address/model/event/EventDateTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/storage/XmlAdaptedEventTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.high, type.bug

#79 Update UserGuide and Fix several Event-related Bugs
  README.adoc
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/main/java/seedu/address/model/event/EndTime.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
Labels: priority.high, type.bug
